/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_studiodomino_scanner_twain_JTwain */

#ifndef _Included_com_studiodomino_scanner_twain_JTwain
#define _Included_com_studiodomino_scanner_twain_JTwain
#ifdef __cplusplus
extern "C" {
#endif
#undef com_studiodomino_scanner_twain_JTwain_RC_SUCCESS
#define com_studiodomino_scanner_twain_JTwain_RC_SUCCESS 0L
#undef com_studiodomino_scanner_twain_JTwain_RC_FAILURE
#define com_studiodomino_scanner_twain_JTwain_RC_FAILURE 1L
#undef com_studiodomino_scanner_twain_JTwain_RC_CHECKSTATUS
#define com_studiodomino_scanner_twain_JTwain_RC_CHECKSTATUS 2L
#undef com_studiodomino_scanner_twain_JTwain_RC_CANCEL
#define com_studiodomino_scanner_twain_JTwain_RC_CANCEL 3L
#undef com_studiodomino_scanner_twain_JTwain_RC_DSEVENT
#define com_studiodomino_scanner_twain_JTwain_RC_DSEVENT 4L
#undef com_studiodomino_scanner_twain_JTwain_RC_NOTDSEVENT
#define com_studiodomino_scanner_twain_JTwain_RC_NOTDSEVENT 5L
#undef com_studiodomino_scanner_twain_JTwain_RC_XFERDONE
#define com_studiodomino_scanner_twain_JTwain_RC_XFERDONE 6L
#undef com_studiodomino_scanner_twain_JTwain_RC_ENDOFLIST
#define com_studiodomino_scanner_twain_JTwain_RC_ENDOFLIST 7L
#undef com_studiodomino_scanner_twain_JTwain_RC_INFONOTSUPPORTED
#define com_studiodomino_scanner_twain_JTwain_RC_INFONOTSUPPORTED 8L
#undef com_studiodomino_scanner_twain_JTwain_RC_DATANOTAVAILABLE
#define com_studiodomino_scanner_twain_JTwain_RC_DATANOTAVAILABLE 9L
#undef com_studiodomino_scanner_twain_JTwain_CC_SUCCESS
#define com_studiodomino_scanner_twain_JTwain_CC_SUCCESS 0L
#undef com_studiodomino_scanner_twain_JTwain_CC_BUMMER
#define com_studiodomino_scanner_twain_JTwain_CC_BUMMER 1L
#undef com_studiodomino_scanner_twain_JTwain_CC_LOWMEMORY
#define com_studiodomino_scanner_twain_JTwain_CC_LOWMEMORY 2L
#undef com_studiodomino_scanner_twain_JTwain_CC_NODS
#define com_studiodomino_scanner_twain_JTwain_CC_NODS 3L
#undef com_studiodomino_scanner_twain_JTwain_CC_MAXCONNECTIONS
#define com_studiodomino_scanner_twain_JTwain_CC_MAXCONNECTIONS 4L
#undef com_studiodomino_scanner_twain_JTwain_CC_OPERATIONERROR
#define com_studiodomino_scanner_twain_JTwain_CC_OPERATIONERROR 5L
#undef com_studiodomino_scanner_twain_JTwain_CC_BADCAP
#define com_studiodomino_scanner_twain_JTwain_CC_BADCAP 6L
#undef com_studiodomino_scanner_twain_JTwain_CC_BADPROTOCOL
#define com_studiodomino_scanner_twain_JTwain_CC_BADPROTOCOL 9L
#undef com_studiodomino_scanner_twain_JTwain_CC_BADVALUE
#define com_studiodomino_scanner_twain_JTwain_CC_BADVALUE 10L
#undef com_studiodomino_scanner_twain_JTwain_CC_SEQERROR
#define com_studiodomino_scanner_twain_JTwain_CC_SEQERROR 11L
#undef com_studiodomino_scanner_twain_JTwain_CC_BADDEST
#define com_studiodomino_scanner_twain_JTwain_CC_BADDEST 12L
#undef com_studiodomino_scanner_twain_JTwain_CC_CAPUNSUPPORTED
#define com_studiodomino_scanner_twain_JTwain_CC_CAPUNSUPPORTED 13L
#undef com_studiodomino_scanner_twain_JTwain_CC_CAPBADOPERATION
#define com_studiodomino_scanner_twain_JTwain_CC_CAPBADOPERATION 14L
#undef com_studiodomino_scanner_twain_JTwain_CC_CAPSEQERROR
#define com_studiodomino_scanner_twain_JTwain_CC_CAPSEQERROR 15L
#undef com_studiodomino_scanner_twain_JTwain_CC_DENIED
#define com_studiodomino_scanner_twain_JTwain_CC_DENIED 16L
#undef com_studiodomino_scanner_twain_JTwain_CC_FILEEXISTS
#define com_studiodomino_scanner_twain_JTwain_CC_FILEEXISTS 17L
#undef com_studiodomino_scanner_twain_JTwain_CC_FILENOTFOUND
#define com_studiodomino_scanner_twain_JTwain_CC_FILENOTFOUND 18L
#undef com_studiodomino_scanner_twain_JTwain_CC_NOTEMPTY
#define com_studiodomino_scanner_twain_JTwain_CC_NOTEMPTY 19L
#undef com_studiodomino_scanner_twain_JTwain_CC_PAPERJAM
#define com_studiodomino_scanner_twain_JTwain_CC_PAPERJAM 20L
#undef com_studiodomino_scanner_twain_JTwain_CC_PAPERDOUBLEFEED
#define com_studiodomino_scanner_twain_JTwain_CC_PAPERDOUBLEFEED 21L
#undef com_studiodomino_scanner_twain_JTwain_CC_FILEWRITEERROR
#define com_studiodomino_scanner_twain_JTwain_CC_FILEWRITEERROR 22L
#undef com_studiodomino_scanner_twain_JTwain_CC_CHECKDEVICEONLINE
#define com_studiodomino_scanner_twain_JTwain_CC_CHECKDEVICEONLINE 23L
#undef com_studiodomino_scanner_twain_JTwain_PT_BW
#define com_studiodomino_scanner_twain_JTwain_PT_BW 0L
#undef com_studiodomino_scanner_twain_JTwain_PT_GRAY
#define com_studiodomino_scanner_twain_JTwain_PT_GRAY 1L
#undef com_studiodomino_scanner_twain_JTwain_PT_RGB
#define com_studiodomino_scanner_twain_JTwain_PT_RGB 2L
#undef com_studiodomino_scanner_twain_JTwain_PT_PALETTE
#define com_studiodomino_scanner_twain_JTwain_PT_PALETTE 3L
#undef com_studiodomino_scanner_twain_JTwain_PT_CMY
#define com_studiodomino_scanner_twain_JTwain_PT_CMY 4L
#undef com_studiodomino_scanner_twain_JTwain_PT_CMYK
#define com_studiodomino_scanner_twain_JTwain_PT_CMYK 5L
#undef com_studiodomino_scanner_twain_JTwain_PT_YUV
#define com_studiodomino_scanner_twain_JTwain_PT_YUV 6L
#undef com_studiodomino_scanner_twain_JTwain_PT_YUVK
#define com_studiodomino_scanner_twain_JTwain_PT_YUVK 7L
#undef com_studiodomino_scanner_twain_JTwain_PT_CIEXYZ
#define com_studiodomino_scanner_twain_JTwain_PT_CIEXYZ 8L
/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    acquire
 * Signature: ()[Ljava/awt/Image;
 */
JNIEXPORT jobjectArray JNICALL Java_com_studiodomino_scanner_twain_JTwain_acquire
  (JNIEnv *, jclass);

/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    closeDS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_studiodomino_scanner_twain_JTwain_closeDS
  (JNIEnv *, jclass);

/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    closeDSM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_studiodomino_scanner_twain_JTwain_closeDSM
  (JNIEnv *, jclass);

/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    getCC
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_studiodomino_scanner_twain_JTwain_getCC
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    getDefaultDS
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_studiodomino_scanner_twain_JTwain_getDefaultDS
  (JNIEnv *, jclass);

/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    getFirstDS
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_studiodomino_scanner_twain_JTwain_getFirstDS
  (JNIEnv *, jclass);

/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    getNextDS
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_studiodomino_scanner_twain_JTwain_getNextDS
  (JNIEnv *, jclass);

/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    getPixelType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_studiodomino_scanner_twain_JTwain_getPixelType
  (JNIEnv *, jclass);

/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    getPixelTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_studiodomino_scanner_twain_JTwain_getPixelTypes
  (JNIEnv *, jclass);

/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    getRC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_studiodomino_scanner_twain_JTwain_getRC
  (JNIEnv *, jclass);

/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    openDS
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_studiodomino_scanner_twain_JTwain_openDS
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    openDSM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_studiodomino_scanner_twain_JTwain_openDSM
  (JNIEnv *, jclass);

/*
 * Class:     com_studiodomino_scanner_twain_JTwain
 * Method:    setPixelType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_studiodomino_scanner_twain_JTwain_setPixelType
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
